### ISSUE TITLE
Already existing overrides get replaced

### ISSUE THREAD

**Issue by dsdsdsdsdsds** [Lebioda/PrestaShop-modules-CleanURLs#1]
If there are already overrides within PrestaShop (e.g. from ProductController.php), the module will replace all code inside the override file during installation (instead of just adding its own code to it).

I also noticed that the module requests writing permissions on the override files during installation. And if it doesn't have them, the installation is aborted. I never had this problem with other modules (who also place code within the override directory).

**Comment by Lebioda** [comment]
Thanks for report! "Install" and "Uninstall" features were added by someone from prestashop.com/forums.

I will check how to use overriding in proper way.

**Comment by ghost** [comment]
@Lebioda are you still active on this project? .. just to know how to help you to develop and fix this usefull module ;)

**Comment by Lebioda** [comment]
Now I don't have time to make changes in this module. It works correctly
for my purposes. When I finish my eshop, I will come back to fix bugs from
community.

**Comment by ghost** [comment]
ok, so I'll keep my fixed altogether on my fork .. thank you

2014-02-18 Lebioda notifications@github.com:

> Now I don't have time to make changes in this module. It works correctly
> for my purposes. When I finish my eshop, I will come back to fix bugs from
> community.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Lebioda/PrestaShop-modules-CleanURLs/issues/1#issuecomment-35376962
> .

## 

_the ZiZuu staff_

**Comment by ghost** [comment]
An updated working fork is at https://github.com/ZiZuu-store/zzCleanURLs
